### PR TITLE
refactor: features | update

### PR DESCRIPTION
**Pull request by DianaGawel**

### CODE REVIEW

**Comment by zaiste** [comment]
@DianaGawel why did you change file permission from `644` to `755` ? this is wrong

**Comment by DianaGawel** [comment]
@zaiste Sorry, I don't know what you mean. There happened a lot of things connected to this commit. Bartek and Tomek were helping me

**Comment by zaiste** [comment]
@DianaGawel can you run `chmod -R 644 website/images/*`

**Comment by DianaGawel** [comment]
@zaiste But what next?

**Comment by DianaGawel** [comment]
@zaiste I run that, what more should I do?

**Comment by zaiste** [comment]
@DianaGawel commit and push to this branch with force. What's your origin ?

**Comment by DianaGawel** [comment]
@zaiste done

**Comment by zaiste** [comment]
@DianaGawel good job!

**Pull request merged**
